
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cpcodingdb
    username: postgres
    password: cpcoding
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true
server:
  port: 8087



